Task4 - Creating SQL DB
tensegrity666/nodejs-aws-backend pull request #2
Opened 2020-11-07 16:29 UTC by tensegrity666

2020-11-10 07:09 UTC, IDiamondDragon reviewed
When i go to this link https://jqnaa7z9ua.execute-api.eu-west-1.amazonaws.com/dev/product/c528cb4b-b705-4ed2-b15c-a0355bb5eaf1 I have got not one product but two object 

[
[
{
"id": "c528cb4b-b705-4ed2-b15c-a0355bb5eaf1",
"title": "Fox",
"description": "Short Product Description 2",
"picture": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQhOVE6UDSrtvlD46SF1MB-k-h1177aASQhZg&usqp=CAU",
"price": 49
}
],
[
{
"id": "1368f59e-3fac-450d-9146-f6c07b153aae",
"list_id": "c528cb4b-b705-4ed2-b15c-a0355bb5eaf1",
"count": 7
}
]
]

but we need to get one object

*FE: One product model as a result of BE models join(product and it's stock) *

  Product model example on Frontend side: 

  {
    id: '19ba3d6a-f8ed-491b-a192-0a33b71b38c4',
    count: 2
    price: 200,
    title: ‘Product Title’,
    description: ‘This product ...’
  }

Something like this https://584prtl1u5.execute-api.eu-west-1.amazonaws.com/dev/products/a731e308-a346-4607-a8fc-724efeb68502

2020-11-10 19:08 UTC, Anisotropic commented on product-service/src/postgress-handlers/get-by-id.js
> +    where id = '${event.pathParameters.id}'`);
Where is JOIN 'stocks' table to read "counts"?

2020-11-11 18:22 UTC, LittleCryingGirl commented
I suggest that 'Your own Frontend application is integrated with product service' means not only get request at main page, but also page
https://d4b3oofc3xqi9.cloudfront.net/admin/products

and after new product created on https://d4b3oofc3xqi9.cloudfront.net/admin/product-form app should successfully request all products after redirect

2020-11-11 18:24 UTC, LittleCryingGirl requested changes
need to add count field
need to implement admin/products page

2020-11-30 20:42 UTC, merged